DDLS-208
ministryofjustice/opg-digideps pull request #1611
Opened 2024-06-18 16:50 UTC by MiaGordon91

## Purpose
_Briefly describe the purpose of the change, and/or link to the JIRA ticket for context_

Fixes DDLS-####

## Approach
_Explain how your code addresses the purpose of the change_

## Learning
_Any tips and tricks, blog posts or tools which helped you. Plus anything notable you've discovered about DigiDeps_

## Checklist
- [ ] I have performed a self-review of my own code
- [ ] I have updated documentation (Confluence/ADR/tech debt doc) where relevant
- [ ] I have added tests to prove my work
- [ ] The product team have approved these changes
- [ ] I have checked my work for potential security issues and refered to the [OWASP top 10](https://owasp.org/www-project-top-ten/)

### Frontend
- [ ] I have run an in-browser accessibility test (e.g. WAVE, Lighthouse)
- [ ] There are no deprecated CSS classes noted in the profiler
- [ ] Translations are used and the profiler doesn't identify any missing
- [ ] Any links or buttons added are screen reader friendly and contextually complete
- [ ] If adding GA events, I have updated or [checked](docs/runbooks/GOOGLE-ANALYTICS.md) the existing category or label values

2024-06-19 15:01 UTC, Raffers commented on api/app/composer.json
> +        "cmixin/business-day": "^1.18",
Why are we using an external library that doesn't pull from the GOV Json list? The referenced library doesn't include all bank holidays either, see - https://github.com/kylekatarnls/business-day/blob/dd2e46ec7e036ccd9b818c49183dcbf0b2a43f10/src/Cmixin/Holidays/gb-national.php

Ref - https://www.gov.uk/bank-holidays.json

2024-06-19 15:02 UTC, Raffers requested changes
Why are we using an external library that doesn't pull from the GOV Json list? The referenced library doesn't include all bank holidays either, see - https://github.com/kylekatarnls/business-day/blob/dd2e46ec7e036ccd9b818c49183dcbf0b2a43f10/src/Cmixin/Holidays/gb-national.php

Ref - https://www.gov.uk/bank-holidays.json

2024-06-19 15:06 UTC, Raffers commented
Also, can you include a test that attempts to set a report, that would fall on a bankholiday. So we can confirm that it sets the next business day.

2024-06-20 08:41 UTC, MiaGordon91 commented
This is the package that Sirius use so thought it would be best to use the same one to align our due dates with them. 
The 'gb-engwales' holiday is set, which merges 'gb-national' with additional bank holidays so that they're all accounted for.

2024-07-30 13:27 UTC, Raffers approved these changes

2024-08-06 09:30 UTC, merged