DDPB-3537: Refactor org CSV upload
ministryofjustice/opg-digideps pull request #477
Opened 2020-10-07 20:26 UTC by acsauk-mojd

## Purpose
In preparation for the court order work we need to simplify and prepare the org CSV upload process to support multiple sources and ensure a good level of test coverage. This will free us to make changes more freely when the CourtOrder entity structure is finalised.

Fixes DDPB-3537

## Approach
I've followed some of the same patterns put in place in the LayCSVUploader work that @aiesoftware did. Using a DTO structure allows us to centralise some of the validation and data sanitising that was spread over OrgService. Simplifying the upload steps and moving some of the existing logic to the Client model and report utils hopefully makes the flow easier to understand.

## Checklist
- [x] I have performed a self-review of my own code
- [ ] I have updated documentation (Confluence/ADR/tech debt doc) where relevant
- [x] I have added tests to prove my work
- [ ] The product team have approved these changes

2020-10-12 09:56 UTC, coderste approved these changes

2020-10-12 09:56 UTC, coderste submitted a review, later dismissed

2020-10-19 10:39 UTC, coderste requested changes
Just some PHPDocs blocks missing other than that it's all good :D 👍🏻

2020-10-19 10:39 UTC, coderste commented on api/src/AppBundle/v2/Registration/Uploader/OrgDeputyshipUploader.php
> +    private function handleNamedDeputy(OrgDeputyshipDto $dto)
Missing docs

2020-10-19 10:39 UTC, coderste commented on api/src/AppBundle/v2/Registration/Uploader/OrgDeputyshipUploader.php
> +    private function handleOrganisation(OrgDeputyshipDto $dto)
Same as above

2020-10-19 10:39 UTC, coderste commented on api/src/AppBundle/v2/Registration/Uploader/OrgDeputyshipUploader.php
> +    private function handleClient(OrgDeputyshipDto $dto)
Last one :)

2020-10-19 10:39 UTC, coderste commented on api/src/AppBundle/v2/Registration/Uploader/OrgDeputyshipUploader.php
> +    private function handleReport(OrgDeputyshipDto $dto)
Maybe not :)

2020-10-19 10:53 UTC, Gugandeep reviewed
Latest changes look good to me.

2020-10-19 13:23 UTC, coderste approved these changes
👍🏻

2020-10-22 08:54 UTC, coderste approved these changes

2020-10-22 08:55 UTC, merged