[DDPB-3948] reporting checklist admin behat tests
ministryofjustice/opg-digideps pull request #668
Opened 2021-07-02 08:38 UTC by coderste

Fixes DDPB-3948

2021-07-05 12:14 UTC, acsauk reviewed
So I'm open to being convinced otherwise on this but there's a variable we pass into the template called `submittedEstimateCosts` that only applies to profs with costs that are not fixed. This shows an extra section of the checklist that sums up the costs.

I guess its not really a feature as such but is a variation. The argument could be made that if we do it for this we should also test other conditional sections of the checklist but yeah, looking to see what you/anyone else reviewing this PR has to say ( cc: @Gugandeep @jamesrwarren)

2021-07-05 12:39 UTC, Gugandeep commented
> So I'm open to being convinced otherwise on this but there's a variable we pass into the template called `submittedEstimateCosts` that only applies to profs with costs that are not fixed. This shows an extra section of the checklist that sums up the costs.
> 
> I guess its not really a feature as such but is a variation. The argument could be made that if we do it for this we should also test other conditional sections of the checklist but yeah, looking to see what you/anyone else reviewing this PR has to say ( cc: @Gugandeep @jamesrwarren)

I think variations of the checklist should be tested since part of the checklists core functionality is having the right questions appearing. Although doesn't necessarily have to be done through behat tests. 
If it's easier (and possible) to do in unit tests by testing `submittedEstimateCosts`  then I'd be happy that would give us enough validity that the code is working fine.

2021-07-05 12:47 UTC, jamesrwarren reviewed
Yep I think conditional parts should be checked using the required user to access them. Do we need to do negative tests as well? That i'm not sure about that but it would be nice to (for example that user X can see section A but user Y can't see section A). As for Gug's suggestion of doing it as part of unit tests... if it's possible and easier then maybe but I feel like behat is more the place for them to be tested as it is part of the user journey. Also happy to be challenged on that! :)

2021-07-05 12:58 UTC, coderste commented
I feel like I agree an oversight on my part about the the checklist form being different depending on the type of client it is. I feel like a single negative test may also be plausible around `client health welfare has section Y but Pfa high assets does not have section Y` just to make sure we are not seeing an incorrect checklist for certain clients.

2021-07-26 14:28 UTC, acsauk requested changes
Couple of small changes but otherwise good to go now it's covering the variations 🙌

2021-07-26 14:28 UTC, acsauk commented on api/tests/Behat/features-v2/reporting/admin/checklist/checklist.feature
> +    Scenario: An lay hw checklist cannot see the pub auth specific sections - applies to all admin roles
The wording on the three new scenarios could be a little clearer here (if I'm understanding it right!) 

Something like:

```
A Lay hw checklist does not contain public authority specific sections - applies to all admin roles
```

What do you think?

2021-07-27 10:06 UTC, jamesrwarren approved these changes
Seems you've sorted all Alex's comments :)

2021-07-27 10:20 UTC, acsauk approved these changes
Great stuff, LGTM! :shipit:

2021-07-28 09:27 UTC, merged