[DDPB-3951] behat rewrite for admin app notifications
ministryofjustice/opg-digideps pull request #680
Opened 2021-08-09 08:41 UTC by coderste

## Purpose
behat rewrite for admin app notifications

Fixes DDPB-##3951#

2021-08-09 19:45 UTC, acsauk requested changes
Looking good - couple of small changes then ready to merge 💪

2021-08-09 19:45 UTC, acsauk commented on api/tests/Behat/behat.yml
> +            description: Coverage of organisation management features - adding, deleting, editing
This needs updating I think 😄

2021-08-09 19:45 UTC, acsauk commented on api/tests/Behat/bootstrap/v2/AppNotification/AppNotificationTrait.php
> +    public function iNavigateToTheClientsSearchPage()
This also needs updating 😹

2021-08-09 19:45 UTC, acsauk commented on api/tests/Behat/bootstrap/v2/AppNotification/AppNotificationTrait.php
> +        assert(null == $el);
Probably best to stay consistent with our assert calls - `AssertTrait::assertIsNull()` should work here

2021-08-09 19:45 UTC, acsauk commented on api/tests/Behat/bootstrap/v2/AppNotification/AppNotificationTrait.php
> +        assert('Lorem ipsum' == $notification);
You can use AssertTrait::assertStringEqualsString() here (for consistency sake - it does the same thing).

2021-08-09 19:45 UTC, acsauk commented on api/tests/Behat/bootstrap/v2/AppNotification/AppNotificationTrait.php
> +        assert('Lorem ipsum' == $notification);
As per others below - `AssertTrait::assertStringEqualsString()` would be good here for consistency.

2021-08-10 08:32 UTC, coderste commented on api/tests/Behat/behat.yml
> +            description: Coverage of organisation management features - adding, deleting, editing
Indeed it does

2021-08-10 08:33 UTC, coderste commented on api/tests/Behat/bootstrap/v2/AppNotification/AppNotificationTrait.php
> +    public function iNavigateToTheClientsSearchPage()
Yep 😆

2021-08-17 08:16 UTC, acsauk approved these changes
:shipit:

2021-08-17 08:45 UTC, merged