DDPB-3525: Created a function to unarchive client from admin
ministryofjustice/opg-digideps pull request #787
Opened 2022-03-09 14:33 UTC by MiaGordon91

## Purpose
To allow high level admin users to unarchive a client for a deputy. A client may have been unarchived incorrectly or needs to be reported on by another deputy.

Fixes DDPB-3525

## Checklist
- [x] I have performed a self-review of my own code
- [ ] I have updated documentation (Confluence/ADR/tech debt doc) where relevant
- [x] I have added tests to prove my work
- [ ] The product team have approved these changes

2022-03-09 15:38 UTC, acsauk requested changes
Great job - this should save us a bunch of time doing manual DB updates 💪 

A few commented out sections that we can drop and some context/tense update for the behat but overall looking nearly ready!

2022-03-09 15:38 UTC, acsauk commented on api/tests/Behat/bootstrap/v2/ClientManagement/ClientManagementTrait.php
> +        $clientId = $this->interactingWithUserDetails->getClientId();
To make the use of this step more friendly we probably want to call `$this->assertInteractingWithUserIsSet();` here too so any future users of the code will get a useful failure error is the user details aren't set.

2022-03-09 15:38 UTC, acsauk commented on api/tests/Behat/bootstrap/v2/ClientManagement/ClientManagementTrait.php
> +        $this->iAmOnAdminClientDetailsPage();
Are we actually asserting on anything here? If we're displaying a flash message or something similar we could assert on that instead.

2022-03-09 15:38 UTC, acsauk commented on api/tests/Behat/features-v2/client-management/admin/unarchive.feature
> +    Scenario: An admin manager user can unarchived a client
```suggestion
    Scenario: An admin manager user can unarchive a client
```

2022-03-09 15:38 UTC, acsauk commented on api/tests/Behat/features-v2/client-management/admin/unarchive.feature
> +        When I visit the admin client archived page
There could be a little more context around this line - something like:

```suggestion
        When I visit the admin client archived page for the user I'm interacting with
```

2022-03-09 15:38 UTC, acsauk commented on client/src/Service/Client/Internal/ClientApi.php
> +    private const UNARCHIVED_CLIENT = 'client/%s/unarchived';
Should this be `UNARCHIVE_CLIENT` and `'client/%s/unarchive'`?

2022-03-09 15:38 UTC, acsauk commented on client/templates/Admin/Client/Client/details.html.twig
> +        {#        {% endif %} #}
Looks like we can drop this now

2022-03-09 15:42 UTC, coderste commented on api/src/Controller/ClientController.php
> +        // if the client is not in the database null then return NotFoundHttpException
Haha yeah that's my bad I was teaching Mia about writing pseudo code :D

2022-03-09 16:07 UTC, acsauk commented on api/tests/Behat/bootstrap/v2/ClientManagement/ClientManagementTrait.php
> +        $this->iAmOnAdminClientDetailsPage();
Ah OK gotcha 👍

2022-03-09 16:09 UTC, acsauk submitted a review, later dismissed
:shipit:

2022-03-11 16:58 UTC, acsauk approved these changes
:shipit:

2022-03-14 10:18 UTC, merged