DdPB 3342 - Add audit log around creation of organisations
ministryofjustice/opg-digideps pull request #824
Opened 2022-05-03 13:17 UTC by MiaGordon91

Create a record when organisations are created so the PM is aware of when they were initially added.

Fixes DDPB-3342

## Approach
- New event and subscriber has been created for the creation of organisations
- AuditEvents has been updated
- EventDispatcher has been added to the manual process and CSV upload options available when creating an organisation in the admin side of the app 

## Checklist
- [x] I have performed a self-review of my own code

2022-05-03 15:30 UTC, acsauk requested changes
Excellent work 🙌  this all looks great and gets us the logs where we need them. Could we get a couple of tests for:

- `AuditEvents::orgCreated()`
- `OrgCreatedSubscriber::getSubscribedEvents()`
- `OrgCreatedSubscriber:: auditLog()`

2022-05-03 15:30 UTC, acsauk commented on client/src/Service/Audit/AuditEvents.php
> +            'current_user' => $currentUser->getEmail(),
I think this is more like `created_by` as in either case it will be someone uploading a CSV or clicking a button.

2022-05-03 15:30 UTC, acsauk commented on api/src/v2/Registration/Uploader/OrgDeputyshipUploader.php
> +            $this->added['organisations'][] = $organisation;
Hmmm, we may need to see what impact this has when running at scale. If we have 1000s of orgs in here we may get out of memory errors.

2022-05-03 15:30 UTC, acsauk commented on client/src/EventSubscriber/OrgCreatedSubscriber.php
> +        DateTimeProvider $dateTimeProvider
We can use constructor property promotion here to remove some boilerplate:

```suggestion
        private LoggerInterface $logger,
        private DateTimeProvider $dateTimeProvider
```

And then drop lines 15-19 and 25-26.

2022-05-03 15:30 UTC, acsauk commented on client/src/Service/Audit/AuditEvents.php
> +            'created_on' => $this->dateTimeProvider->getDateTime()->format(DateTime::ATOM),
Good level of context added here 👍

2022-05-12 12:56 UTC, coderste approved these changes

2022-05-13 09:25 UTC, acsauk approved these changes
Great job :shipit: 

Although lets hold off merging until we've released the CSV code 👍

2022-05-17 10:13 UTC, merged